---
name: Build and push to Docker Hub


on:
  push:
    branches:
      - axions
 

jobs:
  build-image:
    name: Build Image
    runs-on: langchain/langchain
    steps:
            
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Docker build
        uses: docker/build-push-action@v4
        with:
          file: ./bot.Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: axionsdocker32/bot:latest
